### PR TITLE
Fix NA IDs and OTC/RAS IDS

### PR DESCRIPTION
**Pull request by Adeiko**
I added a few IDs I had that were as NA before and in a different commit I've added OTC/RAS IDs

### CODE REVIEW

**Comment by tanho63** [comment]
Great, thanks! I’ll review when I’m back from conf, it’ll be probably Wednesday or Thursday

**Comment by Adeiko** [comment]
Also found this 3 guys that have duplicated GSISID on the db_playerids.csv but do not know how to fix it really
00-0016098 Fred Taylor  is not the MFL ID 8058
00-0020270 Correll Buckhalter is not the MFL ID 1286 
00-0019641 Thomas Jones  is not the MFL ID 4722

**Comment by tanho63** [comment]
Narrator: it was not Wednesday August 4 or Thursday August 5th. 

> Also found this 3 guys that have duplicated GSISID on the db_playerids.csv but do not know how to fix it really
00-0016098 Fred Taylor is not the MFL ID 8058
00-0020270 Correll Buckhalter is not the MFL ID 1286
00-0019641 Thomas Jones is not the MFL ID 4722

Pulling this into a new issue.

**Comment by tanho63** [comment]
Actually this looks like a duplicate of #34

**Pull request merged**
