### PR TITLE
espn_id corrections and additions.

### PR DESCRIPTION
**Pull request by TheMathNinja**
Replaced 5 incorrect espn_id values (Ramiz Ahmed, Nick Williams, Randy Gregory were wrong due to MFL API errors, and Michael Carter's were switched in missing_ids file even though MFL had it right).

Also added ~ 600 missing espn_id values by importing carefully from ffscrapr::espn_players() via joins by cleaned player + team. Took steps to maneuver duplicates in full_join.

I wanted to attach my R script but GitHub doesn't support that kind of file as an attachment. I'll just copy-paste my code below so you can check it and test it further. I'm willing to keep working on this in case there are any edge cases my code misses because the 600 missing ids are quite useful to me. But I do think my checking for duplicates and conservative approach with a left_join at the last step should minimize any errors.

```
#Read in Missing IDs file from Dynasty Process
old_missingplayerids <- jsonlite::fromJSON("https://raw.githubusercontent.com/dynastyprocess/data/master/files/missing_ids.json")

#First populate full MFL player list
mfl_names_list <- ffscrapr::mfl_players() %>%
  select(player_id,
         player_name,
         pos,
         team,
         espn_id) %>%
  rename(mfl_id = player_id,
         mfl_pos = pos,
         mfl_name_raw = player_name,
         mfl_team_raw = team) %>%
  mutate(player_name = nflreadr::clean_player_names(mfl_name_raw),
         team = nflreadr::clean_team_abbrs(mfl_team_raw),
         #Change mfl_id type to match original JSON
         mfl_id = as.integer(mfl_id),
         #Change espn_id type to match original JSON
         espn_id = as.integer(espn_id)) %>%
  # Filter out all MFL team position entries
  filter(mfl_id > 999)

# Clean ESPN player list for join
espn_names_list <- ffscrapr::espn_players() %>%
  rename(espn_id = player_id,
         espn_pos = pos,
         espn_name_raw = player_name,
         espn_team_raw = team) %>%
  mutate(player_name = nflreadr::clean_player_names(espn_name_raw),
         team = nflreadr::clean_team_abbrs(espn_team_raw))

# Find errors in mfl_players() espn_id by mapping mfl_players() to espn_players() by joining name and team
# Where test_1 entries are from duplicates above, we need to filter out wrong duplicate
# Where they are not duplicates, we need to overwrite incorrect data

joined_mfl_espn_players_raw <- mfl_names_list %>%
  full_join(., y = espn_names_list,
            by = c("player_name",
                   "team"))

# Test for contradictions in joined list
test_1_contradictions <- joined_mfl_espn_players_raw %>%
  filter(espn_id.x != espn_id.y)
view(test_1_contradictions)

# Test for duplicates in joined list to show which contradictions are from over-joined duplicates
test_2_duplicates <- joined_mfl_espn_players_raw %>%
  group_by(player_name, team) %>%
  filter(n() > 1) %>%
  arrange(player_name, team)
view(test_2_duplicates)

joined_mfl_espn_players_cleaned <- joined_mfl_espn_players_raw %>%
  mutate(espn_id.x = if_else(
    player_name %in% c("Nick Williams", "Randy Gregory", "Ramiz Ahmed") | is.na(espn_id.x),
    espn_id.y,  # Use espn_players() ID to correct errors and overwrite missing values
    espn_id.x   # Otherwise, keep mfl_players() espn_id value
  )) %>%
  #Filter out remaining contradictions from duplicates or team mismatch
  filter(espn_id.x == espn_id.y | is.na(espn_id.x) | is.na(espn_id.y)) %>%
  mutate(espn_id_new = espn_id.x) %>%
  select(-espn_id.x, -espn_id.y)

view(joined_mfl_espn_players_cleaned)

#Next, join these new espn_id's to the missing ID JSON and check for contradictions
complete_join <- old_missingplayerids %>%
  left_join(., y = joined_mfl_espn_players_cleaned %>%
              select(mfl_id, espn_id_new),
            by = "mfl_id")

#Check for contradictions in espn_id; use joined_mfl_espn_players_cleaned for mfl_id reference check
test_1_contradictions_final <- complete_join %>%
  filter(espn_id != espn_id_new)

new_missingplayerids <- complete_join %>%
  mutate(espn_id = if_else(
    is.na(espn_id) | espn_id != espn_id_new,
    espn_id_new,  # Overwrite with espn_id_new if espn_id is NA or not equal to espn_id_new
    espn_id       # Otherwise, keep the original espn_id
  ))

#convert back to json format
new_missingplayerids %>%
  toJSON(pretty = TRUE) %>%
  write(file = "C:/Users/filim/Documents/R/PullRequests/missing_ids.json")
```

### CODE REVIEW

**Comment by TheMathNinja** [comment]
Quick FYI, I alerted MFL of the API errors for Gregory, Williams, and Ahmed, and they said they fixed the Williams & Ahmed errors. Gregory is tricky because he actually has one ESPN ID for his rookie year and one for every subsequent year. The one in MFL currently is rookie, and the one I'm suggesting is his "new" one. I'm not yet seeing this change in mfl_players() output, but I'm guessing that's because it's cached/loaded.

**Comment by tanho63** [comment]
Resolved by #57

**Comment by TheMathNinja** [comment]
Hey @tanho63 I'm still showing 340 missing espn_ids after the latest GSIS update. Do you want me to still enter another pull request to fill in the 340 missing ID's? Looks like missing_ids.json has gsis ID's but not ESPN ID's for the rookies.

**Comment by tanho63** [comment]
Sure, feel free to open another PR on the latest version

**Pull request closed without merging**
